# Generated by Django 2.1.4 on 2019-01-22 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('GFD_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('FIPS_County', models.IntegerField()),
                ('Name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='CountyExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Revenue', models.IntegerField()),
                ('Total_Taxes', models.IntegerField()),
                ('Tot_Sales_Gr_Rec_Tax', models.IntegerField()),
                ('Total_License_Taxes', models.IntegerField()),
                ('Total_Income_Taxes', models.IntegerField()),
                ('Death_and_Gift_Tax', models.IntegerField()),
                ('Docum_and_Stock_Tr_Tax', models.IntegerField()),
                ('Severance_Tax', models.IntegerField()),
                ('Taxes_NEC', models.IntegerField()),
                ('County', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.County')),
            ],
        ),
        migrations.CreateModel(
            name='CountyRevenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1024)),
                ('Year', models.IntegerField()),
                ('Population', models.IntegerField()),
                ('Total_Revenue', models.IntegerField()),
                ('Total_Taxes', models.IntegerField()),
                ('Tot_Sales_Gr_Rec_Tax', models.IntegerField()),
                ('Total_License_Taxes', models.IntegerField()),
                ('Total_Income_Taxes', models.IntegerField()),
                ('Death_and_Gift_Tax', models.IntegerField()),
                ('Docum_and_Stock_Tr_Tax', models.IntegerField()),
                ('Severance_Tax', models.IntegerField()),
                ('Taxes_NEC', models.IntegerField()),
                ('County', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.County')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('FIPS_Code_State', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='StateRevenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1024)),
                ('Year', models.IntegerField()),
                ('Population', models.IntegerField()),
                ('Total_Revenue', models.IntegerField()),
                ('Total_Taxes', models.IntegerField()),
                ('Tot_Sales_Gr_Rec_Tax', models.IntegerField()),
                ('Total_License_Taxes', models.IntegerField()),
                ('Total_Income_Taxes', models.IntegerField()),
                ('Death_and_Gift_Tax', models.IntegerField()),
                ('Docum_and_Stock_Tr_Tax', models.IntegerField()),
                ('Severance_Tax', models.IntegerField()),
                ('Taxes_NEC', models.IntegerField()),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State')),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State'),
        ),
    ]
