# Generated by Django 2.1.3 on 2018-12-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SurveyYr', models.IntegerField()),
                ('Name', models.CharField(max_length=1024)),
                ('Population', models.IntegerField()),
            ],
        ),
    ]
